# Generated by Django 4.1.2 on 2022-10-21 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_permanent', models.IntegerField(unique=True)),
                ('prenom', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=100)),
                ('addresse', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
                ('date_de_naissance', models.IntegerField()),
            ],
        ),
    ]
