# Generated by Django 4.1.1 on 2022-10-21 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Etudiant', '0002_alter_etudiant_date_de_naissance_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='etudiant',
            new_name='Etudiants',
        ),
    ]
